apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stock-app-webshop-evtd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stock-app-webshop-evtd
    app.kubernetes.io/part-of: webshop
  name: stock-app-webshop-evtd
  namespace: rh-ee-jbergfel-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: stock-app-webshop-evtd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: stock-app-webshop-evtd
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:FD1d4-stock-app-webshop-evtd
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
