apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stock-app-webshop-evtd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stock-app-webshop-evtd
    app.kubernetes.io/part-of: webshop
  name: stock-app-webshop-evtd
  namespace: rh-ee-jbergfel-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: stock-app-webshop-evtd
status:
  loadBalancer: {}
