apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: order-app-webshop-cbmv
  namespace: rh-ee-jbergfel-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:FD1d4-order-app-webshop-cbmv
        name: my-java-springboot
        resources: {}
status: {}
